"""Addes a summary column

Revision ID: 00f0c7836969
Revises: 4ff79d7f6bcb
Create Date: 2020-04-25 00:15:38.827143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f0c7836969'
down_revision = '4ff79d7f6bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('summary', sa.String(length=1500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'summary')
    # ### end Alembic commands ###
