"""Addes a image_link column

Revision ID: 1de1fc557ca9
Revises: af360e84f95a
Create Date: 2020-04-25 03:06:19.590481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de1fc557ca9'
down_revision = 'af360e84f95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('image_link', sa.String(length=3000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'image_link')
    # ### end Alembic commands ###
