"""Addes a link column

Revision ID: af360e84f95a
Revises: 00f0c7836969
Create Date: 2020-04-25 01:08:57.460706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af360e84f95a'
down_revision = '00f0c7836969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('wiki_link', sa.String(length=3000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'wiki_link')
    # ### end Alembic commands ###
